### ISSUE TITLE
'Search NGO need' search bar filters by NGO, does not search for a NGO need

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#183]
Starting point: http://dev.rohelp.ro/en/admin/hub/ngoneed/

**Expected**:
Search NGO need by typing in the search functionality a NGO need as specified in Title, Description, Kind or Resource Tag
![Screenshot 2020-03-30 at 19 34 58](https://user-images.githubusercontent.com/61550276/77950859-da095f00-72d1-11ea-980c-73cb7907e352.png)

**Actual**:
Search NGO need functionally gives results only if you type a NGO as Filter by NGO field functions 
![Screenshot 2020-03-30 at 22 01 05](https://user-images.githubusercontent.com/61550276/77951120-3a000580-72d2-11ea-889a-7987e7563fdf.png)

**Steps performed/Reproduction**:
1. Click on the right side of the page http://dev.rohelp.ro/en/admin/hub/ngoneed/ on 
> Search NGO need
2. Type in the field a need as specified in Title, Description, Kind or Resource tag, as example: 
> environment 
> food
> volunteer
> apa
3. Press enter/Click on magnifying glass
4. 0 results  
![Screenshot 2020-03-30 at 22 08 51](https://user-images.githubusercontent.com/61550276/77951688-1db09880-72d3-11ea-9e1b-ef1fb5ed30a1.png)

**Comment by catileptic** [comment]
In order to maintain a symmetry between the functionality in the landing page and the one in the admin panel, let's not add the NGO need description to the list of things you can search by. We decided not to add it in the landing page because the NGO might create different needs for different cities, for example, but they might just copy/paste the description, rendering the search confusing. 

I do agree that we should add:
* need title (the most important)
* tags
* kind

**Comment by catileptic** [comment]
Closed by #189
