### ISSUE TITLE
[admin] Combo boxes for City & County don't check each other in order to correspond 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#198]
Starting point: http://dev.rohelp.ro/en/admin/hub/

**Expected**:
Combo boxes for City & County should check each other in order to be valid for the following submenus:

> NGO needs
> NGO pending requests
> NGO register requests
> NGOs

**Actual**:
Combo boxes for City & County do not correspond 
The user is permitted to type any City even if the City typed in the field does not belong to the 
County selected from the burger menu 

![Screenshot 2020-03-31 at 12 58 29](https://user-images.githubusercontent.com/61550276/78015061-7d4d8900-7351-11ea-9f51-91dd0d0278a2.png)

![Screenshot 2020-03-31 at 12 58 46](https://user-images.githubusercontent.com/61550276/78014919-437c8280-7351-11ea-9f3f-957d8b3e66de.png)

![Screenshot 2020-03-31 at 12 58 55](https://user-images.githubusercontent.com/61550276/78014927-45dedc80-7351-11ea-822d-fdf4d4a95405.png)

![Screenshot 2020-03-31 at 12 59 11](https://user-images.githubusercontent.com/61550276/78014935-48d9cd00-7351-11ea-8b6c-1a076e5801cd.png)

**Comment by catileptic** [comment]
I suspect you will find that this is true in the landing page as well - the Counties don't line up with the Cities. 

This is not due to a fault in the implementation, but due to how we generated random test data. The test data is generated from a `seed` command and doesn't take this into account. In the production environment, the County will filter the Citiy list to only display the cities within the county. 

Is this true in the admin panel as well, @costibleotu?

**Comment by catileptic** [comment]
This will be addressed by #327
