### ISSUE TITLE
No confirmation email for new user 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ro-help#216]
Starting point: http://dev.rohelp.ro/en/admin/auth/user/

**Expected**:
Receiving an email in Inbox/Junk/Spam with the confirmation that the user was created successfully

**Actual**:
No email in Inbox/Junk/Spam with the confirmation that the user was created successfully

**Comment by catileptic** [comment]
I have the very same observations that I stated in #217 .

**Comment by catileptic** [comment]
When an NGO asks to join Ro Help, or when an NGO that was added by the administrators is validated, an e-mail is sent prompting the user to activate the account. An e-mail should not be sent when an admin creates a user without attaching it to an NGO since this is an operations that only ever happens when adding users to the administration groups. 

If we will conclude that we do, indeed, want an e-mail to be sent when a user is added from the admin panel, we will re-open this Issue.
